### ISSUE TITLE
Missing processed NER data/ files

### ISSUE THREAD

**Issue by msclar** [cindyxinyiwang/emea#1]
Hi!

I see that in the README.md it says that processed NER data can be found in the data/ folder, but I cannot find it. I tried to recreate it from other sources but I think I have not been able to recreate it properly.

Could you add it to the repo or provide a link to it? I am working on modifying EMEA for a binary classification task and it would help me a lot to debug the code.

Thanks,
Melanie

**Comment by cindyxinyiwang** [comment]
Hi,

Sorry I forgot to add it. You should be able to find it now!
